<?php
$ajaxHelper = $this->helper('weltpixel_ajaxsearch');
$minimalCharacters = $ajaxHelper->getMinimalCharacters();
$headerText = $ajaxHelper->getHeaderText();
$footerText = $ajaxHelper->getFooterText();

/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper = $this->helper('catalogsearch');

$_formAction = $catalogSearchHelper->getResultUrl();
$_inputName = $catalogSearchHelper->getQueryParamName();
$_inputValue = $catalogSearchHelper->getEscapedQueryText();
$_inputMaxLength = $catalogSearchHelper->getMaxQueryLength();
$_inputPlaceholder = $this->__('Find products on rent ?');
?>
<form id="wpas-form" class="search-v2-form" action="<?php echo $_formAction; ?>" method="get" style="display: block;">
<div class="input-group">
  <input type="text" id="wpas-q" name="<?php echo $_inputName; ?>" autocomplete="on" value="<?php echo $_inputValue; ?>"
  maxlength="<?php echo $_inputMaxLength; ?>" placeholder="<?php echo $_inputPlaceholder; ?>" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
<div id="wpas-loader"></div>
  <span class="input-group-addon" id="basic-addon2">  <i class="icon icon-line-search"></i></span>
</div>
<div id="wpas-ajax" style="display:none;">
    <?php if (strlen($headerText)): ?>
        <div id="wpas-header"><?php echo $headerText; ?></div>
    <?php endif; ?>
    <div id="wpas-title"><?php echo $this->__('Search result(s)'); ?> : <span id="wpas-count"></span> <?php echo $this->__('item(s)'); ?></div>
    <div id="wpas-items"></div>
    <?php if (strlen($footerText)): ?>
        <div id="wpas-footer"><?php echo $footerText; ?></div>
    <?php endif; ?>
</div>
    </form>

    <script>
            //<![CDATA[
            var WeltPixel = WeltPixel || {};
            WeltPixel.AjaxSearch = {
                url: "<?php echo $this->getUrl('ajaxsearch/products'); ?>",
                minChars: <?php echo $minimalCharacters; ?>
            };

            document.observe('dom:loaded', function() {
                WeltPixel_AjaxSearch.init(WeltPixel.AjaxSearch.url, WeltPixel.AjaxSearch.minChars);
            });

            WeltPixel_AjaxSearch.bindEvents();

            //]]>
        </script>
