<?php
/**
 * Medma Marketplace
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magento Team
 * that is bundled with this package of Medma Infomatix Pvt. Ltd.
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Contact us Support does not guarantee correct work of this package
 * on any other Magento edition except Magento COMMUNITY edition.
 * =================================================================
 *
 * @category    Medma
 * @package     Medma_MarketPlace
**/
?>

<?php $_order = $this->getOrder() ?>
<?php
    $orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
    $orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<div class="box-left">
    <!--Order Information-->
    <div class="entry-edit">
        <?php if ($_order->getEmailSent()):
            $_email = Mage::helper('sales')->__('the order confirmation email was sent');
        else:
            $_email = Mage::helper('sales')->__('the order confirmation email is not sent');
        endif; ?>
        <div class="entry-edit-head">
        <?php if ($this->getNoUseOrderLink()): ?>
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?> (<?php echo $_email ?>)</h4>
        <?php else: ?>
            <a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
            <strong>(<?php echo $_email ?>)</strong>
        <?php endif; ?>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                <td class="value"><strong><?php echo $orderAdminDate ?></strong></td>
            </tr>
            <?php if ($orderAdminDate != $orderStoreDate):?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
                <td class="value"><strong><?php echo $orderStoreDate ?></strong></td>
            </tr>
            <?php endif;?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                <td class="value"><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
            </tr>
			<tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                <td class="value"><strong><?php echo $this->getOrderStoreName() ?></strong></td>
            </tr>
            <?php if($_order->getRelationChildId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the New Order') ?></label></td>
                <td class="value"><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                    <?php echo $_order->getRelationChildRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRelationParentId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the Previous Order') ?></label></td>
                <td class="value"><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                    <?php echo $_order->getRelationParentRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRemoteIp() && $this->shouldDisplayCustomerIp()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
                <td class="value"><strong><?php echo $_order->getRemoteIp(); echo ($_order->getXForwardedFor())?' (' . $this->escapeHtml($_order->getXForwardedFor()) . ')':''; ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td class="value"><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td class="value"><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->

</div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->

</div>
<?php if (!$this->getOrder()->getIsVirtual()): ?>
<div class="box-right">
    <!--Shipping Address-->
  
</div>
<div class="clear"></div>
<?php endif; ?>
