<?php
$_isHomepage = $this->getIsHomePage();
$_logoAlt = $this->getLogoAlt();
$_logoUrl = $this->getUrl('');
$_logoSrc = $this->getLogoSrc();
?>


<header id="page-header" class="row v2" style="background-color: white !important;">
  <div class="col-md-1 col-xs-2 " >
      <!--  <php echo $this->getChildHtml('logo'); ?>  -->
          <a href="<?php echo $_logoUrl; ?>"><img src="<?php echo $_logoSrc; ?>" alt="<?php echo $_logoAlt; ?>" style="width:100%;" /></a>
  </div>
  <div class="col-md-10 col-xs-10">
    <div id="page-header-section-01" style="background-color: white !important;">
        <div class="w header-container" style="margin-right: 0px;">

          <span  class="header-settings"><i class="icon-user"></i></span>
          <div class="header-options">

              <?php echo $this->getChildHtml('website_switcher') ?>
              <?php echo $this->getChildHtml('store_language_flag') ?>
              <?php echo $this->getChildHtml('custom_currency_selector') ?>
              <?php echo $this->getChildHtml('topLinks'); ?>
          </div>

        </div>
    </div>
    <div id="page-header-section-02">


      <div class="col-md-9 col-xs-10">

  <?php echo $this->getChildHtml('search'); ?>

      <!--  <ul  id="quick-search" >icon icon-line-menu
          <li class="first">

          </li>
        </ul> -->

      </div>
      <div class="col-md-3 col-xs-2 cartAddjust">
        <?php echo $this->getChildHtml('quickAccess'); ?>
      </div>

  </div>


  </div>

</header>
<div id="endHeader" class="v2"></div>
<?php echo $this->getChildHtml('topContainer'); ?>
