<header id="page-header" class="v2">
    <div id="page-header-section-01">
        <div class="w header-container">
          <?php echo $this->getChildHtml('quickAccess'); ?>
        	<span  class="header-settings"><i class="icon-user"></i></span>
        	<div class="header-options">
        		<?php echo $this->getChildHtml('topLinks'); ?>
              <?php echo $this->getChildHtml('store_switcher') ?>
	            <?php echo $this->getChildHtml('store_language_flag') ?>
	            <?php echo $this->getChildHtml('custom_currency_selector') ?>
        	</div>

        </div>
    </div>
    <div id="page-header-section-02">
		<div class="w row">
      <div class="col-md-3">
        	<?php echo $this->getChildHtml('logo'); ?>
      </div>
      <div class="col-md-6">
        <ul  id="quick-search" >
          <li class="first">
              <?php echo $this->getChildHtml('search'); ?>
          </li>
        </ul>

      </div>

		</div>
  </div>
</header>
<div id="endHeader" class="v2"></div>
<?php echo $this->getChildHtml('topContainer'); ?>
