<?php
$disableCompare = Mage::getStoreConfig('weltpixel_selector/headeroptions/disable_compare');
?>
<ul id="quick-access" style="top: 0px;position: relative;">

    <li class="mini-cart first">
        <?php echo $this->getChildHtml('cart'); ?>
    </li>
    <?php if (!$disableCompare): ?>
    <li class="mini-compare last">
        <?php echo $this->getChildHtml('product_compare_block'); ?>
    </li>
    <?php endif; ?>
</ul>
