<style>


</style>
<script>
function redirect(url){
  document.location=url;
}
</script>
<div class="col-md-12 col-xs-12" style="padding-left: 15%;margin-bottom: 2%;margin-top: 6%;">
<?php
$websites = Mage::getModel('core/website')->getCollection();
foreach($websites as $website)
{Mage::log($website->debug(),Zend_log::INFO,'layout.log',true);
    $default_store = $website->getDefaultStore();
    $url_obj = new Mage_Core_Model_Url();
    $default_store_path = $url_obj->getBaseUrl(array('_store'=> $default_store->getCode()));
?>
    <div onClick="redirect('<?= $default_store_path ?>');" class="col-md-3 col-xs-3 cityCircle" <?php if($website['is_default']==1):?>
      style=" opacity: 1; background-color: #11C638;"  <?php endif; ?> value="<?php echo $default_store_path ?>" >
      <?php echo $website->getName()?>
    </div>
<?php
}
?>
</div>
