<?php
$_coreHelper = $this->helper('core');
$_product = $this->getProduct();
$_qty = $this->getProductDefaultQty() * 1;
$_renttime = $_product->getData('renttime')*1;
Mage::log($_product->debug(),Zend_log::INFO,'layout.log',true);
?>

<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if ( ! $_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Quantity:'); ?></label>
        <a href="javascript: void(0);" class="qty-dec qty-disabled"><i class="icon-angle-left"></i></a>
        <input type="number" name="qty" id="qty" value="<?php echo $_qty; ?>" title="" class="input-text qty" />
        <a href="javascript: void(0);" class="qty-inc"><i class="icon-angle-right"></i></a>
        <?php endif; ?>

        <div class="row" style="margin-bottom: 2%;">
                <label for="renttime"><?php echo $this->__('Duration');
                $att = $_product->getResource()->getAttribute('renttype')->getFrontend()->getValue($_product);
                $keywords = preg_split("/[\s,]+/", $att);

                echo  ' ('.$keywords[1].'):' ?></label>
                <a href="javascript: void(0);" class="renttime-dec qty-disabled"><i class="icon-angle-left"></i></a>
                <input type="number" name="renttime" id="renttime" value="<?php echo $_renttime; ?>" title="" class="input-text renttime" />
                <a href="javascript: void(0);" class="renttime-inc"><i class="icon-angle-right"></i></a>

            <!--    <input type="hidden" id="renttype" value="<php echo $_product->getResource()->getAttribute('renttype')->getFrontend()->getValue($_product); ?>" />
                <input type="hidden" id="mintime" value="<php echo  $_product->getData('mintime') ?>" />

                  <div class="input-group input-daterange">
                      <input type="text" class="form-control" name="fromdate" id="fromdate">
                        <span class="input-group-addon">to</span>
                      <input type="text" class="form-control" name="todate" id="todate">
                  </div>  -->
        </div>
        <div class="row">
            <label for="security"><?php echo $this->__('Security:'); ?></label>
              <label style="font-weight: bold;" class="label pull-right"><?php echo  $_coreHelper->formatPrice($_product->getData('security'), false) ?> </label>
        </div>
        <div class="row">
            <label for="notice"><?php echo $this->__('Notice Period:'); ?></label>
              <label style="font-weight: bold;" class="label pull-right">
                <?php  if($_product->getData('noticeperiod')){
                              echo  $_product->getData('noticeperiod');
                          }else{
                          echo  ' N/A';} ?>
              </label>
        </div>
        <div class="actions">
            <button type="button" class="button" id="product-addtocart-button" onclick="productAddToCartForm.submit(this)">
                <span><i class="icon icon-shopping-cart"></i><?php echo $this->__('Add to Cart'); ?></span>
            </button>
        </div>
        <?php echo $this->getChildHtml('', true, true); ?>
    </div>
<?php endif; ?>
