<?php
$_product = $this->getProduct();
$_qty = $this->getProductDefaultQty() * 1;
?>

<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if ( ! $_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Quantity:'); ?></label>
        <a href="javascript: void(0);" class="qty-dec qty-disabled"><i class="icon-angle-left"></i></a><input type="number" name="qty" id="qty" value="<?php echo $_qty; ?>" title="" class="input-text qty" /><a href="javascript: void(0);" class="qty-inc"><i class="icon-angle-right"></i></a>
        <?php endif; ?>
        <div class="row">
            <label for="mintime"><?php echo $this->__('Min time:'); ?></label>
                <label class="label pull-right"><?php echo  $_product->getData('mintime') ?> Months</label>
        </div>
        <div class="row" style="margin-bottom: 2%;">
                <input type="hidden" id="renttype" value="<?php echo $_product->getResource()->getAttribute('renttype')->getFrontend()->getValue($_product); ?>" />
                <input type="hidden" id="mintime" value="<?php echo  $_product->getData('mintime') ?>" />

                  <div class="input-group input-daterange">
                      <input type="text" class="form-control" name="fromdate" id="fromdate">
                        <span class="input-group-addon">to</span>
                      <input type="text" class="form-control" name="todate" id="todate">
                  </div>
        </div>
        <div>
            <label for="security"><?php echo $this->__('Security:'); ?></label>
              <label class="label pull-right"><?php echo  number_format($_product->getData('security')) ?> </label>
        </div>
        <div class="actions">
            <button type="button" class="button" id="product-addtocart-button" onclick="productAddToCartForm.submit(this)">
                <span><i class="icon icon-shopping-cart"></i><?php echo $this->__('Add to Cart'); ?></span>
            </button>
        </div>
        <?php echo $this->getChildHtml('', true, true); ?>
    </div>
<?php endif; ?>
